if(location.protocol!='https:'){location.protocol='https:';}
$(` <center><div style=" width: 100%;height: auto!important; "  id="as" margin: 2px;" class="fa fa-heartbeat btn btn-danger" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">&nbsp;● · мυsɪc · ●&nbsp;</div><div class="collapse" id="collapseExample"><center><div class="well"><p lass="bg-primary"></i></p>اغاني</p><audio controls loop="" play=""><source src="https://iraqiachats.com/iqr30.mp3"></audio></div><center>`).insertBefore('label.nosel.ninr.fl.uzr.label.label-primary'),
$(`<img src ="iraqqq.jpg" etclass="fr" style="width:100%;margin-top: 1px;"><div id="asim10"><center><a id="asim33" href="contact.html" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">اتصل بنا</a><a id="asim33" href="mobile.html" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">التطبيق</a><a id="asim33" href="sub.html" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">اشتراكات</a><a id="asim33" href="Shortcut.html" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">اختصارات</a><a id="asim33" href="style1.html" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">زخرفة</a><a id="asim33" href="rules.html" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">القوانين<a id="asim33" href="ruless.html" target="_blank" type="button" style=" width: 22%; margin: 2px;" class="btn btn-primary btn-sm">المراقبين<a id="asim32" href="https://iraqiachats.com" target="_blank" type="button" style=" width: 18%; margin: 2px;" class="fa fa-viadeo btn btn-primary btn-sm"> المدونة<a id="asim31" href="https://iraqiachats.com/vb" target="_blank" type="button" style=" width: 18%; margin: 2px;" class="fa fa-viadeo btn btn-primary btn-sm"> المنتدى<a id="asim29" href="" target="_blank" type="button" style=" width: 18%; margin: 2px;" class="fa fa-viadeo btn btn-primary btn-sm"> عراقنا<a id="asim32" href="https://iraqiachats.com" target="_blank" type="button" style=" width: 18%; margin: 2px;" class="fa fa-viadeo btn btn-primary btn-sm"> المدونة<a id="asim31" href="https://iraqiachats.com/vb" target="_blank" type="button" style=" width: 18%; margin: 2px;" class="fa fa-viadeo btn btn-primary btn-sm"> المنتدى<a id="asim29" href="" target="_blank" type="button" style=" width: 18%; margin: 2px;" class="fa fa-home fa fa-viadeo btn btn-primary btn-sm"> عراقنا<a id="asim30" target="_blank" type="button" style=" margin-top:-117px!important;margin-left:280.5px!important;width: 21%; margin: 2px;" class=""><img src ="sico/z1cddvpnu510.gif" etclass="fr" style="width:110%;"><center>`).insertBefore('.nav-tabs'),$('.checkbox label').html(`<input id="stealth" type="checkbox" value=""><img style="width: 22px;" src="IQ/5.gif" width="100%">`),$('.nav-tabs').addClass('fl').css('width','100%'),$('.tc span[class="fa fl"]').addClass('fa-check'),$(`<link rel="stylesheet" href="as2.css"><style>
.fitimg.fl.u-pic {
    border-radius: 4px;
    border: 1px solid transparent;
    padding: 16px;
    border-image: url(sico/z1ccppo1j810.png) 1 stretch;}
</style>`).insertBefore('body'),
$('.fa.fa-user-plus').html(`تسجيل`);(document.getElementById("tbox").placeholder = "عمي عوف السطح ودردش ويانا");
$(`<a href="Shortcut.html" target="_blank" style=" font-family: 'El Messiri', sans-serif;width:107px;color: #E8415D;text-decoration:none; margin-right: 5px;margin-left: 2px;text-align: center;float: right;border-radius: 5px;border-color: #F2F2F2;padding: 3px;" class="border" ><i class="fa fa-reddit-alien"></i>&nbsp;اختصارات</a>`).insertBefore('a.fl.fa.fa-ban.btn.ui-corner-all.ui-shadow.ui-btn.ui-btn-inline.umute.borderg');var nopm = !0;var nonot = !0;
$(`<center><div><marquee direction="right" width="99%" id="asim8" onmouseover="this.stop()" onmouseout="this.start()" scrolldelay="0" scrollamount="5">  &nbsp;مبارك علينا وعليكم شهر رمضان شهر الخير والمغفره وندعو من الله عز وجل أن يجعل هذا الشهر خيراً على عراقنا الحبيب - آهلا وسهلا بكم في شات <font class="a"> عــراقــنــا</font> ● · افضل سوبر  · ●<font class="a"> ديـــمـــآ </font> ● · افضل زائر  · ●<font class="a"> جعـفـر المحمداوي </font> ● · افضل زائرة  · ●<font class="a"> مــآرسلــيــن </font> ● · مبدع الحائط · ●<font class="a"> عــمــوري </font> ● · مبدعة الحائط · ● <font class="a"> شـآمخـة رغـم آلآلــم </font> ● · افضل تواجد · ●<font class="a"> هجران الصبر </font> ● · مع تمنياتنا للجميع بـ أطيب الاوقات&nbsp;
</marquee></div><center>`).insertBefore('div#tlogins .lonline.light.break');
